baseurl = "https://shadowrz.github.io/blog/"
languageCode = "zh-cn"
paginate = 20
title = "RC0S % Blog"
subtitle = "A place for Yorusaka Miyabi"

enableInlineShortcodes = true
enableRobotsTXT = true

DefaultContentLanguage = "en"
hasCJKLanguage = true

uglyurls = true

copyright = "2021-2023 Yorusaka Miyabi"
disableKinds = ["taxonomy"]

[minify]
disableXML = true
minifyOutput = true

[permalinks]
posts = "/posts/:filename"

[outputs]
home = [ "HTML" ]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[markup.goldmark.renderer]
unsafe = true

[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

# Theme params
[params]
env = 'production'
mainSections = [ "posts" ]
#description = "A place for Yorusaka Miyabi"
author = "Yorusaka Miyabi"
# author = '夜坂雅'

ShowReadingTime = true
ShowWordCount = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = false
# comments = false

[params.assets]
theme_color = "#9d174d"
