baseurl = "https://shadowrz.github.io/blog/"
languageCode = "zh-cn"
title = "@ShadowRZ's Blog"
subtitle = "A Place Somewhere"

enableInlineShortcodes = true
enableRobotsTXT = true

DefaultContentLanguage = "en"
hasCJKLanguage = true

uglyurls = true

copyright = "2021-2025 Yorusaka Miyabi"
disableKinds = ["taxonomy"]

[minify]
disableXML = true
minifyOutput = true

[permalinks]
posts = "/posts/:contentbasename"

[outputs]
home = [ "HTML" ]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[markup.goldmark.renderer]
unsafe = true

[[module.imports]]
path = "github.com/g1eny0ung/hugo-theme-dream"

# Theme params
[params]
env = "production"
lightTheme = "pastel"
darkTheme = "sunset"
noDefaultSummaryCover = true
author = "ShadowRZ"
avatar = "images/avatar.png"
headerTitle = "@ShadowRZ's Blog"
motto = "A Place Somewhere"
siteStartYear = 2021
reorderNavItems = ["posts"]
