baseurl = "https://shadowrz.github.io/blog/"
languageCode = "zh-cn"
paginate = 20
title = "RC0S % Blog"
subtitle = "A place for Yorusaka Miyabi"

enableInlineShortcodes = true
enableRobotsTXT = true

DefaultContentLanguage = "en"
hasCJKLanguage = true

uglyurls = true

copyright = "Yorusaka Miyabi"
disableKinds = ["taxonomy"]

[minify]
disableXML = true
minifyOutput = true

[permalinks]
posts = "/posts/:filename"

[outputs]
home = [ "HTML" ]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true

[[module.imports]]
path = "github.com/ShadowRZ/hugo-theme-bookworm-light"

# Theme params
[params]
mainSections = [ "posts" ]
description = "A place for Yorusaka Miyabi"
logo_text = "RC0S % Blog"
author = "Yorusaka Miyabi"
copyright = "2021-2023 Yorusaka Miyabi  \nTheme: [Bookworm Light](https://github.com/ShadowRZ/hugo-theme-bookworm-light) Designed & Developed By [Gethugothemes](https://gethugothemes.com/) with my own modifications."

[params.variables]
font_primary = "Jost"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#152035"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/@fontsource/jost/latin.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"