baseurl = "https://shadowrz.github.io/blog/"
languageCode = "zh-cn"
title = "@ShadowRZ's Blog"
subtitle = "Where something happens."

enableInlineShortcodes = true
enableRobotsTXT = true

DefaultContentLanguage = "en"
hasCJKLanguage = true

uglyurls = true

copyright = "2021-2025 Yorusaka Miyabi"
disableKinds = ["taxonomy"]

[minify]
disableXML = true
minifyOutput = true

[permalinks]
posts = "/posts/:contentbasename"

[outputs]
home = [ "HTML" ]

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[markup.goldmark.renderer]
unsafe = true
