allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.10.4'
  - '@astrojs/markdown-satteri@0.3.7'
  - astro@7.2.4
  - '@astrojs/markdown-remark@7.2.4'
  - '@astrojs/mdx@7.0.7'
  - '@astrojs/markdown-satteri@0.4.1'
  - astro@7.3.2
  - '@astrojs/mdx@8.0.1'
